language: android
android:
  components:
  - platform-tools
  - extra
  - android-22
  - build-tools-22.0.1
script:
- gradle clean build
notifications:
  slack:
    secure: XXj2RwAakzzrR81dpUZUomWenbeKHhtb9ueWBcNIw48wF9eMvmnpqVk5uPN8/fQQpwjtWj60zza55/jsUPcW65q1o4pk8B8uLvDb8tTvXO0iqPiws9dobL3rttfabv17ZLA/mvlqT3eM1y+h6yBFtDGiy1KOMpbFtk0rj5NDnb5Rdf3dUjsDySUvIYaizn8iV6F/kCKfQXjDSf3k0ZEB5W672cFRQCsngshbc9F4+njfam6vqaG14xR/MoFWRjrttIv/bUY5BOaknJQhFXCuti7ppSLAB5UAcEREYpwXUfln63XR+e2dX2DS1d8Hfx/kMZXNApxPYxlvaSjfU9yaeqEb1KJvBdI9lOVxYyqSnOaw/3nmrZ3Y+kk8AD42R4yxVtasFKMO1gaPTy7eKtvFOCp+53HYEJ+hsbeO9/C9lnX6Ca4UpZzGOdJztmb7yAdhxtR9vxCDVlsj9Zv9VcP9ZYETauA5TTXAsJV+jgdHGgKFJOF8o/8QVpCBTrKwFBbh0XTrlkALr+xghCNGRHdRco+6BG6pWp3l9RoB4BSLO+YAcEcl3JgVgMtvpUKvDYoFp59S/QQXUfvwpAWn15wUnTfSS52k3Ilj/gHaXkw//5qErWBxl6/bsT6+8rDwf7eET4uGXr9ClNJYFOqibqypTs43Jh4errFbP8FaEmnE6ks=
  email:
    recipients:
    - jak@microsoft.com
    on_success: never
    on_failure: always
